# Generated by Django 5.1.6 on 2025-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(verbose_name='created')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('operation', models.CharField(max_length=200)),
                ('answer', models.FloatField(default=0.0)),
            ],
        ),
    ]
